### PR TITLE
Link Mozilla l10n style guides

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by MikkCZ** [comment]
@JustOff r?

**Comment by wolfbeast** [comment]
Mozilla's style guides are (as per usual) overly-generic and not providing the necessary guidance to come to a proper, coherent and consistent localization for Pale Moon.
If anything, we should write our own style guide based on community feedback.

**Comment by MikkCZ** [comment]
The style guides are written by individual Mozilla l10n communities (do not look on the general style guide only). So the quality and level of generality of course varies for each language. To my experience, a single style guide needs to be pretty generic if you want to apply it for all languages, as they can fundamentally differ and of course one document cannot cover all locales specifics.

**Comment by wolfbeast** [comment]
Sorry but I beg to differ. I've done 7 years of translation work and you _can_ write a single style guide for all languages - in fact you _should_, if you want your result to be consistent _regardless_ of target language. As such linking to Mozilla's guide is a bad idea.

Thanks for your suggestion but I simply can't agree with it.

**Pull request closed without merging**
