### PR TITLE
[cs] - minor fix, fix typo (+ additional information about the problem)

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
__ad [en-US/browser/chrome/AB-CD/locale/browser/devtools/gcli.properties](https://github.com/MoonchildProductions/pale-moon-localization/blob/master/en-US/browser/chrome/AB-CD/locale/browser/devtools/gcli.properties#L301)__

disconnectDesc = connectDesc
disconnectManual = connectManual

They contain the same string - it is probably bug.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Please do not use "smart quotes" in properties files.

**Comment by wolfbeast** [comment]
Actually, it's probably okay to do so since everything is UTF-8 now. can you test if it's causing issues in operation or display?

**Comment by janekptacijarabaci** [comment]
I changed it. I see no problem...

**Comment by wolfbeast** [comment]
If there's no problem, then changing all the quotes wasn't needed. I didn't realize there were already plenty of smart quotes in there. Sorry for the confusion. Can you revert the last commit to your PR please?

**Comment by wolfbeast** [comment]
Thank you!

**Pull request merged**
