### PR TITLE
pl & cs locales update

### PR DESCRIPTION
**Pull request by JustOff**

### CODE REVIEW

**Comment by janekptacijarabaci** [comment]
Thank you. Unfortunately, character encoding of the files *.properties is broken :-/

**Comment by JustOff** [comment]
@janekptacijarabaci no, it's not broken, try to install [xpi](https://github.com/JustOff/pale-moon-localization/releases/tag/27.0.0_RC1)

**Comment by janekptacijarabaci** [comment]
I'm sorry, but it's broken. Later I will add screenshots... (I'm currently busy)

**Comment by JustOff** [comment]
@janekptacijarabaci oops ... looks like I found the cause

**Pull request closed without merging**
